---
driver:
  name: dokken
  chef_version: 17.6.18 
  privileged: true
  pid_one_command: /bin/systemd

transport:
  name: dokken

provisioner:
  name: dokken
  chef_license: accept

verifier:
  name: inspec

platforms:
- name: centos-stream-8
  driver:
    image: dokken/centos-stream-8
    pid_one_command: /usr/lib/systemd/systemd
    privileged: true
    
- name: centos-8
  driver:
    image: dokken/centos-8
    pid_one_command: /usr/lib/systemd/systemd
    privileged: true

suites:
  - name: latest
    run_list:
    - recipe[cobbler3::default]
    - recipe[cobbler3_test::default]
