---
driver:
  name: dokken
  chef_version: 17.6.18 
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken
  privileged: true

verifier:
  name: inspec

platforms:
- name: centos-stream-8
  driver:
    image: dokken/centos-stream-8
    pid_one_command: /usr/lib/systemd/systemd
- name: centos-8
  driver:
    image: dokken/centos-8
    pid_one_command: /usr/lib/systemd/systemd 

suites:
  - name: latest
    run_list:
    - recipe[cobbler3::default]
    - recipe[cobbler3_test::default]
