# Workflow used for testing the cobbler3 cookbook

name: cobbler3-cookbook-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    # Use the Ubuntu runner and spin up a Chef Workstation Docker container
    runs-on: ubuntu-20.04
    container:
      image: chef/chefworkstation:21.12.724 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Analyzes code for linting issues using new cookstyle. Fail if ANY issues are found 
      - name: Run Cookstyle
        run: cookstyle . --fail-level R

      # Converge cookbook using dokken and execute Inspec tests
      - name: Run Integration Tests using Kitchen
        run: kitchen verify
