# Workflow used for testing the cobbler3 cookbook

name: cobbler3-cookbook-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    # Use the Ubuntu runner and spin up a Chef Workstation Docker container
    runs-on: ubuntu-latest
    container:
      image: chef/chefworkstation:22.1.772

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Analyzes code for linting issues using new cookstyle. Fail if ANY issues are found 
      - name: Run Cookstyle
        run: | 
          cookstyle . --fail-level R
          if [ $? -ne 0 ]; then
            echo "Issues found when running cookstyle - review output and fix all issues before pushing again"
          else
            echo "cookstyle ran and found no issues"
          fi

      # Converge cookbook using dokken and execute Inspec tests
      - name: Run Integration Tests using Kitchen
        run: |
          kitchen verify
          if [ $? -ne 0 ]; then
            echo "The cookbook failed to converge or verify - review output and fix all issues before pushing again"
          else
            echo "The cookbook passed all converges and verifications"
          fi           
